name: frontend
description: Explore the wonders of the universe with Lunar Glimpse
publish_to: 'none'

version: 1.1.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  astro_common:
    path: ../common
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.0.0
  drift: ^2.20.3
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_blurhash: ^0.8.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  lottie: ^3.1.2
  material_color_utilities: ^0.11.1
  package_info_plus: ^8.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  share_plus: ^10.0.3
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  super_sliver_list: ^0.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/flags/
    - assets/app_logos/
