targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - unused_local_variable
            - invalid_use_of_internal_member
            - unnecessary_null_comparison
            - unnecessary_non_null_assertion
      drift_dev:
        options:
          sql:
            dialects:
              - postgres