targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - unused_local_variable
      drift_dev:
        options:
          sql:
            dialects:
              - postgres