name: astro_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  astro_common:
    path: ../common
  cloudinary: ^1.2.0
  csv: ^6.0.0
  dart_frog: ^1.1.0
  drift: ^2.19.1+1
  drift_postgres: ^1.3.0
  image: ^4.2.0
  intl: ^0.19.0
  logger: ^2.3.0
  postgres: ^3.2.1

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.19.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
