name: astro_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  astro_common:
    path: ../common
  dart_frog: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  postgres: ^3.2.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
